---
title: "Blood Pressure"
output:
  html_document:
    df_print: paged
params:
  output_dir: "docs"
---

Read and preprocess latest blood-pressure file.
```{r message=FALSE}
library(lubridate)
```
```{r}
b <- read.csv(file="bp.csv", header=TRUE, sep=",")
f <- read.csv(file="factors.csv", header=TRUE, sep=",")
bp <- merge(b, f)
bp$datetime <- as_datetime(paste(bp$date, bp$time))
mp <- c(min(bp$dia), max(bp$sys))
cdia <- rgb(0,0,1,1/4)
csys <- rgb(1,0,0,1/4)
cpul <- rgb(0,1,0,1/4)
```
A function to plot blood pressure histograms:
```{r}
plot.blood.pressure <- function(bp, title) {
  hsys <- hist(bp$sys, plot=F)
  hdia <- hist(bp$dia, plot=F)
  mc <- c(0, max(c(hsys$counts, hdia$counts)))
  plot(hdia, col=cdia, xlim=mp, ylim=mc, main = paste(title, " (", as.Date(min(bp$datetime)), " to ", as.Date(max(bp$datetime)), ")", sep=""), xlab = "mmHg")
  plot(hsys, col=csys, xlim=mp, ylim=mc, add=T)
  mdia <- mean(bp$dia)
  msys <- mean(bp$sys)
  abline(v=c(msys, mdia), col=c("red","blue"))
  legend("topright", bty="n", legend=c(paste("sys: ", format(msys, digits=2)), paste("dia: ", format(mdia, digits=2))))
}
```

## Overall
Plot systolic and diastolic pressures for all data points.
```{r}
plot.blood.pressure(bp, "Overall")
```

### Recent
Over the last four weeks:
```{r}
recent <- day(max(bp$datetime)) - day(bp$datetime) < 28
plot.blood.pressure(bp[recent,], "Recently")
```

### Morning
```{r}
am <- hour(bp$datetime) < 12
plot.blood.pressure(bp[am,], "Morning")
```

### Evening
```{r}
pm <- hour(bp$datetime) >= 12
plot.blood.pressure(bp[pm,], "Evening")
```

### Work days
```{r}
plot.blood.pressure(bp[bp$work == 1,], "Work")
```

### Holidays
```{r}
plot.blood.pressure(bp[bp$work == 0,], "Holidays")
```

### Over Time

Systolic and diastolic blood pressure over time.
```{r}
movavg <- function(x, n=5){
  filter(x,rep(1/n,n), sides=2)
}
plot.dates <- function(bp, var, title, col, yl="mmHg") {
  cs <- c("green", "blue")
  dates <- bp$datetime
  points <- bp[,var]
  plot(dates[am], points[am], xlab="Date", ylab=yl, main=title, col=cs[1])
  lines(dates[am], movavg(points[am], 7), col=cs[1])
  lines(dates[pm], movavg(points[pm], 7), col=cs[2])
  abline(v=dates[wday(dates) %in% c(1,7)], col="lightgray")
  sd <- lm(points~dates)
  abline(sd, col=col)
  points(dates[am], points[am], col=cs[1])
  points(dates[pm], points[pm], col=cs[2])
  legend("bottomright", bty="n", legend=paste("r^2: ", format(summary(sd)$r.squared, digits=2)))
  legend("bottomleft", bty="n", legend=c("am", "pm"), text.col = cs, pt.bg=cs)
}
plot.dates(bp, "sys", "Systolic", "red")
plot.dates(bp, "dia", "Diastolic", "blue")
```

## Systolic vs Diastolic Pressure

```{r}
plot(bp$dia, bp$sys, xlab = "Diastolic", ylab="Systolic")
msd <- lm(bp$sys~bp$dia)
abline(msd)
legend("bottomright", bty="n", legend=paste("r^2: ", format(summary(msd)$r.squared, digits=2)))
```

## Pulse

```{r}
plot.pulse <- function(pulse, c, title) {
  hpul <- hist(pulse, plot=F)
  plot(hpul, col=c, main = title, xlab = "bpm")
  m <- mean(pulse)
  abline(v=m, col=c)
  legend("topright", bty="n", legend=paste("av: ", format(m, digits=2)))
}
plot.pulse(bp$pul, cpul, "Overall")
```

### Morning

```{r}
plot.pulse(bp[am,]$pul, cpul, "Morning")
```

### Evening

```{r}
plot.pulse(bp[pm,]$pul, cpul, "Evening")
```

### Over Time

```{r}
plot.dates(bp, "pulse", "Pulse", "green", "bpm")
```


